# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/eda/Project/rooth/fpga/rooth/rooth.cache/wt [current_project]
set_property parent.project_path /home/eda/Project/rooth/fpga/rooth/rooth.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/eda/Project/rooth/fpga/rooth/rooth.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/rooth_defines.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/alu_core.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/alu_res_ctrl.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/clinet.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/csr_reg.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/decode.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/div.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/flow_ctrl.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/perips/gpio.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/if_as.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/if_de.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/if_ex.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/if_wb.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/imm_gen.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/mux_alu.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/pc_reg.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/reg_clash_fb.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/regs_file.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/bus/rib.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/core/rooth.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/perips/spi.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/perips/timer.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/perips/uart.v
  /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/imports/rtl/soc/rooth_soc.v
}
read_ip -quiet /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

read_ip -quiet /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all /home/eda/Project/rooth/fpga/rooth/rooth.srcs/sources_1/ip/clk_pll/clk_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top rooth_soc -part xc7k325tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rooth_soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rooth_soc_utilization_synth.rpt -pb rooth_soc_utilization_synth.pb"
