# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rooth_xdc.xdc

# Block Designs: bd/flash_rooth/flash_rooth.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_rooth || ORIG_REF_NAME==flash_rooth} -quiet] -quiet

# IP: bd/flash_rooth/ip/flash_rooth_processing_system7_0_0/flash_rooth_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_rooth_processing_system7_0_0 || ORIG_REF_NAME==flash_rooth_processing_system7_0_0} -quiet] -quiet

# IP: ip/inst_mem/inst_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_mem || ORIG_REF_NAME==inst_mem} -quiet] -quiet

# XDC: bd/flash_rooth/flash_rooth_ooc.xdc
