# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado_prj/flash_rooth/flash_rooth.cache/wt [current_project]
set_property parent.project_path D:/Vivado_prj/flash_rooth/flash_rooth.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado_prj/flash_rooth/flash_rooth.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Vivado_prj/flash_rooth/program/demo.coe
add_files D:/Vivado_prj/flash_rooth/program/spi_lcd.coe
add_files d:/Vivado_prj/flash_rooth/program/spi_oled.coe
read_verilog -library xil_defaultlib {
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/rooth_defines.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/alu_core.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/alu_res_ctrl.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/clinet.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/csr_reg.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/decode.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/div.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/flow_ctrl.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/jtag/full_handshake_rx.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/jtag/full_handshake_tx.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/perips/gpio.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/if_as.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/if_de.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/if_ex.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/if_wb.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/imm_gen.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/jtag/jtag_dm.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/jtag/jtag_driver.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/jtag/jtag_top.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/mux_alu.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/pc_reg.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/reg_clash_fb.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/regs_file.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/bus/rib.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/core/rooth.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/soc/rooth_soc.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/perips/spi.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/perips/timer.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rtl/perips/uart.v
  D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/hdl/flash_rooth_wrapper.v
}
add_files D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/flash_rooth.bd
set_property used_in_implementation false [get_files -all d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/ip/flash_rooth_processing_system7_0_0/flash_rooth_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/flash_rooth_ooc.xdc]

read_ip -quiet D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/clk_pll_1/clk_pll.xci
set_property used_in_implementation false [get_files -all d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/clk_pll_1/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/clk_pll_1/clk_pll.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/clk_pll_1/clk_pll_ooc.xdc]

read_ip -quiet D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rooth_xdc.xdc
set_property used_in_implementation false [get_files D:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/user/rooth_xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top flash_rooth_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef flash_rooth_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file flash_rooth_wrapper_utilization_synth.rpt -pb flash_rooth_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
