# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/ip/flash_rooth_processing_system7_0_0/flash_rooth_processing_system7_0_0.xci
# IP: The module: 'flash_rooth_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/ip/flash_rooth_processing_system7_0_0/flash_rooth_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_rooth_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/ip/flash_rooth_processing_system7_0_0/flash_rooth_processing_system7_0_0.xci
# IP: The module: 'flash_rooth_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_prj/flash_rooth/flash_rooth.srcs/sources_1/bd/flash_rooth/ip/flash_rooth_processing_system7_0_0/flash_rooth_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_rooth_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
